Responsive-TableV2
kittyevi/responsive-table pull request #2
Opened 2022-10-06 14:20 UTC by AlenoJankowsky

PR: #2

2022-10-07 06:12 UTC, DevBastiS requested changes

2022-10-07 06:12 UTC, DevBastiS commented on index.html
> +    <div class="body__table-container">
```suggestion
    <div class="table-container">
```

2022-10-07 06:12 UTC, DevBastiS commented on index.html
> +      <table id="body__table-id" class="table-container__table">
```suggestion
      <table id="table-id" class="table-container__table">
```

2022-10-07 06:12 UTC, DevBastiS commented on script.js
> +function hideTableContents(className) {
```suggestion
function hideColumnContents(className) {
```

2022-10-07 06:12 UTC, DevBastiS commented on script.js
> +  for (let cellIterator = 0; cellIterator < allCellsInClass.length; cellIterator++) {
Do this with a for of loop.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of?retiredLocale=de

2022-10-07 07:57 UTC, MKrips approved these changes

2022-10-07 07:57 UTC, MKrips commented on style.css
> +}
you can you use classes you gave your elements for this or create a new class (one for header and one for cells) and style them

2022-10-10 06:26 UTC, DevBastiS approved these changes

2022-10-10 06:35 UTC, merged